package com.aiman.smartwardrobe.data.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * ============================================================================
 * CALENDAR_EVENT Entity — Records each time a wardrobe item is worn.
 * ============================================================================
 *
 * <p>This entity functions as a <b>wear log</b> that tracks the usage
 * history of every clothing item in the wardrobe. Each record creates a
 * link between a specific {@link WardrobeItem} and the date it was worn.</p>
 *
 * <p><b>This data powers two critical features:</b></p>
 *
 * <ol>
 *   <li><b>Smart Stylist — Recency Filter (Module 3):</b>
 *       When generating an outfit, the algorithm queries this table to
 *       find items worn in the last 3 days and EXCLUDES them from
 *       recommendations. This promotes outfit variety and prevents
 *       the user from wearing the same items repeatedly.
 *       <pre>
 *       SQL: SELECT DISTINCT item_id FROM calendar_event
 *            WHERE date_worn >= :threeDaysAgo
 *       </pre>
 *   </li>
 *
 *   <li><b>Analytics Dashboard — Cost-Per-Wear (Module 4):</b>
 *       The number of CalendarEvent records for an item represents its
 *       total wear count. The Cost-Per-Wear (CPW) metric is:
 *       <pre>
 *       CPW = WardrobeItem.purchasePrice / COUNT(CalendarEvent for that item)
 *       </pre>
 *       Items with low CPW are "high value" (worn frequently relative to cost).
 *   </li>
 * </ol>
 *
 * <p><b>Foreign Key Relationship:</b>
 * Each CalendarEvent references a WardrobeItem via {@code item_id}.
 * The {@code CASCADE} delete strategy ensures that when a wardrobe item
 * is deleted, ALL of its associated wear history records are automatically
 * removed, maintaining referential integrity.</p>
 *
 * <p><b>Index:</b> An index on {@code item_id} is created to optimize
 * the frequent JOIN and WHERE queries on this foreign key column.</p>
 *
 * <p><b>Table Name:</b> calendar_event</p>
 * <p><b>Primary Key:</b> event_id (auto-generated)</p>
 *
 * @author Aiman — Final Year Project
 * @version 1.0
 * @see com.aiman.smartwardrobe.data.entity.WardrobeItem
 * @see com.aiman.smartwardrobe.data.dao.CalendarEventDao
 */
@Entity(
    tableName = "calendar_event",
    foreignKeys = {
        @ForeignKey(
            entity = WardrobeItem.class,
            parentColumns = "item_id",
            childColumns = "item_id",
            onDelete = ForeignKey.CASCADE
        ),
        @ForeignKey(
            entity = UserProfile.class,
            parentColumns = "user_id",
            childColumns = "user_id",
            onDelete = ForeignKey.CASCADE
        )
    },
    indices = {
        @Index(value = "item_id"),
        @Index(value = "user_id")
    }
)
public class CalendarEvent {

    // =========================================================================
    // COLUMN DEFINITIONS
    // =========================================================================

    /**
     * Unique identifier for this calendar event / wear record.
     * Auto-generated by Room using SQLite's AUTOINCREMENT.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "event_id")
    private long eventId;

    /**
     * Foreign key referencing the {@link WardrobeItem#itemId} that was worn.
     * This creates a many-to-one relationship: one WardrobeItem can have
     * many CalendarEvent records (worn on many different days).
     */
    @ColumnInfo(name = "item_id")
    private long itemId;

    @ColumnInfo(name = "user_id")
    private long userId;

    /**
     * The date the item was worn, stored as milliseconds since Unix epoch.
     *
     * <p><b>Why epoch milliseconds?</b>
     * Using long (epoch millis) instead of a formatted date string enables
     * efficient range queries in SQL:
     * <pre>
     *   WHERE date_worn >= :threeDaysAgoMillis
     * </pre>
     * This is critical for the Smart Stylist's "recently worn" filter,
     * which needs to quickly find all items worn within the last N days.</p>
     *
     * <p>To convert to a human-readable date:
     * {@code new Date(dateWorn)} or use {@code SimpleDateFormat}.</p>
     */
    @ColumnInfo(name = "date_worn")
    private long dateWorn;

    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================

    /**
     * Default no-argument constructor.
     * <b>Required by Room</b> for entity instantiation via reflection.
     */
    public CalendarEvent() {
    }

    /**
     * Constructor for creating a new wear record.
     *
     * @param itemId   The ID of the wardrobe item that was worn
     * @param dateWorn The date worn as epoch milliseconds
     */
    @Ignore
    public CalendarEvent(long itemId, long dateWorn) {
        this.itemId = itemId;
        this.dateWorn = dateWorn;
    }

    // =========================================================================
    // GETTERS AND SETTERS
    // =========================================================================

    public long getEventId() {
        return eventId;
    }

    public void setEventId(long eventId) {
        this.eventId = eventId;
    }

    public long getItemId() {
        return itemId;
    }

    public void setItemId(long itemId) {
        this.itemId = itemId;
    }

    public long getDateWorn() {
        return dateWorn;
    }

    public void setDateWorn(long dateWorn) {
        this.dateWorn = dateWorn;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    // =========================================================================
    // UTILITY METHODS
    // =========================================================================

    @Override
    public String toString() {
        return "CalendarEvent{" +
                "eventId=" + eventId +
                ", itemId=" + itemId +
                ", dateWorn=" + dateWorn +
                '}';
    }
}
