package com.aiman.smartwardrobe.data.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * ============================================================================
 * STYLING_ONTOLOGY Entity — The Knowledge Base for the Smart Stylist Engine.
 * ============================================================================
 *
 * <p>This entity stores the <b>deterministic rules</b> that power the
 * automated outfit recommendation system (Module 3). Each record defines
 * a styling rule that maps a dress code context to a set of allowed
 * clothing categories and a temperature threshold.</p>
 *
 * <p><b>"Ontology" Explained:</b>
 * In computer science, an ontology is a formal representation of knowledge
 * within a domain. Here, the StylingOntology encodes the domain knowledge
 * of fashion rules — specifically, which clothing categories are appropriate
 * for which dress codes and weather conditions. This makes the outfit
 * recommendation system <i>deterministic</i> (rule-based) rather than
 * <i>probabilistic</i> (ML-based), which is easier to explain, debug,
 * and validate in a thesis context.</p>
 *
 * <p><b>How Rules Are Applied in the Smart Stylist Algorithm (Module 3):</b></p>
 * <pre>
 * ALGORITHM: Generate Outfit
 * ─────────────────────────────
 * 1. User taps "Generate Outfit" button
 * 2. App fetches current temperature via OpenWeatherMap API
 *    → e.g., currentTemp = 32°C
 *
 * 3. Query StylingOntology:
 *    SELECT * FROM styling_ontology
 *    WHERE max_temperature >= 32
 *    → Returns rules valid for hot weather (e.g., "Casual Summer")
 *
 * 4. Parse allowed_categories from matching rules:
 *    → "T-Shirt,Shorts,Sneakers,Dress,Skirt"
 *
 * 5. Filter wardrobe_item table:
 *    SELECT * FROM wardrobe_item
 *    WHERE category IN ('T-Shirt','Shorts','Sneakers','Dress','Skirt')
 *
 * 6. Exclude recently worn items (last 3 days via CalendarEvent)
 *
 * 7. Select one Top + one Bottom + one Shoes from remaining items
 *
 * 8. Display on the Fit Stylist canvas
 * </pre>
 *
 * <p><b>Design Decision — CSV String for Categories:</b>
 * The {@code allowed_categories} field stores categories as a
 * comma-separated string (e.g., "T-Shirt,Shorts,Sneakers") rather than
 * using a normalized junction table. This simplifies the schema for the
 * FYP scope while still enabling flexible rule definitions. Categories
 * are parsed in the Repository layer using {@code String.split(",")}.</p>
 *
 * <p><b>Pre-seeded Rules Example:</b></p>
 * <pre>
 * | rule_id | dress_code       | allowed_categories                    | max_temperature |
 * |---------|------------------|---------------------------------------|-----------------|
 * | 1       | Casual Hot       | T-Shirt,Shorts,Sneakers,Dress,Skirt   | 45.0            |
 * | 2       | Casual Warm      | T-Shirt,Shirt,Jeans,Pants,Sneakers    | 28.0            |
 * | 3       | Casual Cool      | Hoodie,Sweater,Jeans,Pants,Boots      | 18.0            |
 * | 4       | Formal           | Shirt,Pants,Dress,Shoes               | 35.0            |
 * | 5       | Winter           | Jacket,Sweater,Jeans,Pants,Boots      | 10.0            |
 * </pre>
 *
 * <p><b>Table Name:</b> styling_ontology</p>
 * <p><b>Primary Key:</b> rule_id (auto-generated)</p>
 *
 * @author Aiman — Final Year Project
 * @version 1.0
 * @see com.aiman.smartwardrobe.data.dao.StylingOntologyDao
 * @see com.aiman.smartwardrobe.data.SmartWardrobeDatabase
 */
@Entity(tableName = "styling_ontology")
public class StylingOntology {

    // =========================================================================
    // COLUMN DEFINITIONS
    // =========================================================================

    /**
     * Unique identifier for this styling rule.
     * Auto-generated by Room using SQLite's AUTOINCREMENT.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "rule_id")
    private long ruleId;

    /**
     * The dress code context this rule applies to.
     * Examples: "Casual Hot", "Casual Warm", "Casual Cool", "Formal",
     * "Business Casual", "Sport", "Winter", "Outdoor"
     *
     * <p>In the UI, the user can optionally select a dress code preference.
     * If no preference is set, the system uses temperature alone to find
     * matching rules.</p>
     */
    @ColumnInfo(name = "dress_code")
    private String dressCode;

    /**
     * Comma-separated list of clothing categories allowed for this rule.
     * Example: "Shirt,Pants,Dress Shoes"
     *
     * <p>Parsed in the Repository layer using:
     * {@code Arrays.asList(allowedCategories.split(","))}</p>
     *
     * <p>These categories must match the {@code category} values stored
     * in the {@link WardrobeItem} entity for the filtering to work correctly.</p>
     */
    @ColumnInfo(name = "allowed_categories")
    private String allowedCategories;

    /**
     * Maximum temperature (in Celsius) for which this rule is applicable.
     *
     * <p>The Smart Stylist queries for rules where:
     * {@code max_temperature >= currentTemperature}</p>
     *
     * <p><b>Example:</b> A "Winter" rule with max_temperature = 10.0
     * would only be returned when the current temperature is ≤ 10°C.
     * Conversely, a "Casual Hot" rule with max_temperature = 45.0
     * would be valid for any temperature up to 45°C.</p>
     */
    @ColumnInfo(name = "max_temperature")
    private double maxTemperature;

    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================

    /**
     * Default no-argument constructor.
     * <b>Required by Room</b> for entity instantiation via reflection.
     */
    public StylingOntology() {
    }

    /**
     * Constructor for creating a new styling rule.
     *
     * @param dressCode         The dress code context (e.g., "Formal")
     * @param allowedCategories Comma-separated allowed categories
     * @param maxTemperature    Maximum temperature in Celsius for this rule
     */
    @Ignore
    public StylingOntology(String dressCode, String allowedCategories,
                           double maxTemperature) {
        this.dressCode = dressCode;
        this.allowedCategories = allowedCategories;
        this.maxTemperature = maxTemperature;
    }

    // =========================================================================
    // GETTERS AND SETTERS
    // =========================================================================

    public long getRuleId() {
        return ruleId;
    }

    public void setRuleId(long ruleId) {
        this.ruleId = ruleId;
    }

    public String getDressCode() {
        return dressCode;
    }

    public void setDressCode(String dressCode) {
        this.dressCode = dressCode;
    }

    public String getAllowedCategories() {
        return allowedCategories;
    }

    public void setAllowedCategories(String allowedCategories) {
        this.allowedCategories = allowedCategories;
    }

    public double getMaxTemperature() {
        return maxTemperature;
    }

    public void setMaxTemperature(double maxTemperature) {
        this.maxTemperature = maxTemperature;
    }

    // =========================================================================
    // UTILITY METHODS
    // =========================================================================

    @Override
    public String toString() {
        return "StylingOntology{" +
                "ruleId=" + ruleId +
                ", dressCode='" + dressCode + '\'' +
                ", allowedCategories='" + allowedCategories + '\'' +
                ", maxTemperature=" + maxTemperature +
                '}';
    }
}
