package com.aiman.smartwardrobe.data.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * ============================================================================
 * USER_PROFILE Entity — Represents a user of the Smart Wardrobe system.
 * ============================================================================
 *
 * <p>This entity stores basic user identification and their preferences.
 * The {@code preferences} field stores a JSON string that can contain
 * user-specific settings such as preferred dress codes, favorite colors,
 * and notification preferences.</p>
 *
 * <p><b>Design Decision — JSON String for Preferences:</b>
 * Rather than creating a separate table for each preference type, we store
 * all preferences as a single JSON string. This provides schema flexibility
 * without requiring Room database migrations every time a new preference
 * field is introduced. The JSON is parsed using Google Gson in the
 * Repository layer.</p>
 *
 * <pre>
 * Example JSON structure for the preferences field:
 * {
 *   "preferred_dress_code": "casual",
 *   "favorite_colors": ["#000000", "#FFFFFF", "#1E3A5F"],
 *   "temperature_unit": "celsius",
 *   "notification_enabled": true
 * }
 * </pre>
 *
 * <p><b>Table Name:</b> user_profile</p>
 * <p><b>Primary Key:</b> user_id (auto-generated by SQLite AUTOINCREMENT)</p>
 *
 * @author Aiman — Final Year Project
 * @version 1.0
 * @see com.aiman.smartwardrobe.data.dao.UserProfileDao
 * @see com.aiman.smartwardrobe.data.SmartWardrobeDatabase
 */
@Entity(tableName = "user_profile")
public class UserProfile {

    // =========================================================================
    // COLUMN DEFINITIONS
    // =========================================================================

    /**
     * Unique identifier for the user.
     * Auto-generated by Room using SQLite's AUTOINCREMENT mechanism.
     * This ensures each user gets a unique, ever-increasing ID.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "user_id")
    private long userId;

    /**
     * Display name of the user.
     * Used for personalization throughout the app UI (e.g., "Welcome, Aiman!").
     * This field is NOT NULL by default in Room when using a String type
     * without @Nullable annotation.
     */
    @ColumnInfo(name = "username")
    private String username;

    /**
     * User preferences stored as a JSON string.
     *
     * <p>Using a JSON string allows flexible schema evolution without
     * requiring Room database migrations when new preferences are added.
     * The JSON is serialized/deserialized using Google Gson.</p>
     *
     * @see com.google.gson.Gson
     */
    @ColumnInfo(name = "preferences")
    private String preferences;

    /**
     * Email of the user. Used for login authentication.
     */
    @ColumnInfo(name = "email")
    private String email;

    /**
     * Hashed password of the user.
     */
    @ColumnInfo(name = "password")
    private String password;

    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================

    /**
     * Default no-argument constructor.
     * <p><b>Required by Room:</b> Room uses reflection to instantiate entity
     * objects when reading from the database.</p>
     */
    public UserProfile() {
    }

    /**
     * Convenience constructor for creating a new UserProfile instance.
     *
     * @param username    The display name of the user
     * @param preferences JSON string containing user preferences
     */
    @Ignore
    public UserProfile(String username, String preferences) {
        this.username = username;
        this.preferences = preferences;
    }

    /**
     * Convenience constructor for creating a new UserProfile instance with credentials.
     *
     * @param username    The display name of the user
     * @param email       The email of the user
     * @param password    The hashed password of the user
     * @param preferences JSON string containing user preferences
     */
    @Ignore
    public UserProfile(String username, String email, String password, String preferences) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.preferences = preferences;
    }

    // =========================================================================
    // GETTERS AND SETTERS
    // =========================================================================

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPreferences() {
        return preferences;
    }

    public void setPreferences(String preferences) {
        this.preferences = preferences;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // =========================================================================
    // UTILITY METHODS
    // =========================================================================

    @Override
    public String toString() {
        return "UserProfile{" +
                "userId=" + userId +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", preferences='" + preferences + '\'' +
                '}';
    }
}
