package com.aiman.smartwardrobe.data.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * ============================================================================
 * WARDROBE_ITEM Entity — Represents a single clothing item in the user's
 * digital wardrobe.
 * ============================================================================
 *
 * <p>This is the <b>central entity</b> of the entire Smart Wardrobe system.
 * Every piece of clothing the user photographs and catalogues becomes a
 * WardrobeItem record. The rich metadata captured here powers all four
 * application modules:</p>
 *
 * <ol>
 *   <li><b>Module 1 — Digital Inventory:</b> Items are displayed in a
 *       filterable RecyclerView grid. Each card shows the item image,
 *       category label, and a color indicator dot.</li>
 *
 *   <li><b>Module 2 — Manual Fit Stylist:</b> The user manually picks
 *       items from this table to layer on the outfit canvas. The
 *       {@code image_path} field (pointing to a transparent PNG) is
 *       critical for the visual layering effect.</li>
 *
 *   <li><b>Module 3 — Automated Smart Stylist:</b> The algorithm queries
 *       this table and applies rule-based filtering using {@code category}
 *       and {@code fabric_type} fields against the StylingOntology rules
 *       and current weather data.</li>
 *
 *   <li><b>Module 4 — Analytics Dashboard:</b> The {@code purchase_price}
 *       field is divided by the wear count (from CalendarEvent) to compute
 *       the Cost-Per-Wear metric.</li>
 * </ol>
 *
 * <p><b>Design Decision — Local Image Storage:</b>
 * Images are stored as local file URIs ({@code image_path}) rather than
 * as BLOB data in the database. This follows Android best practices:
 * <ul>
 *   <li>Keeps the SQLite database lightweight and fast</li>
 *   <li>Allows Glide to efficiently cache and load images</li>
 *   <li>Images are stored in the app's internal storage, ensuring they
 *       are private and deleted when the app is uninstalled</li>
 * </ul></p>
 *
 * <p><b>Table Name:</b> wardrobe_item</p>
 * <p><b>Primary Key:</b> item_id (auto-generated)</p>
 *
 * @author Aiman — Final Year Project
 * @version 1.0
 * @see com.aiman.smartwardrobe.data.dao.WardrobeDao
 * @see com.aiman.smartwardrobe.data.entity.CalendarEvent
 * @see com.aiman.smartwardrobe.data.entity.StylingOntology
 */
@Entity(
    tableName = "wardrobe_item",
    foreignKeys = @ForeignKey(
        entity = UserProfile.class,
        parentColumns = "user_id",
        childColumns = "user_id",
        onDelete = ForeignKey.CASCADE
    ),
    indices = @Index(value = "user_id")
)
public class WardrobeItem {

    // =========================================================================
    // COLUMN DEFINITIONS
    // =========================================================================

    /**
     * Unique identifier for this wardrobe item.
     * Auto-generated by Room using SQLite's AUTOINCREMENT.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "item_id")
    private long itemId;

    @ColumnInfo(name = "user_id")
    private long userId;

    /**
     * The clothing category this item belongs to.
     * Examples: "T-Shirt", "Jeans", "Sneakers", "Jacket", "Dress"
     *
     * <p><b>Usage across modules:</b>
     * <ul>
     *   <li><b>Module 1:</b> Filter chips on the wardrobe grid allow the
     *       user to view items by category.</li>
     *   <li><b>Module 2:</b> The Fit Stylist groups items by category
     *       (Tops, Bottoms, Shoes) for outfit composition.</li>
     *   <li><b>Module 3:</b> The Smart Stylist matches categories against
     *       the {@code allowed_categories} field in StylingOntology.</li>
     * </ul></p>
     */
    @ColumnInfo(name = "category")
    private String category;

    /**
     * The dominant color of the item stored as a hex string.
     * Format: "#RRGGBB" (e.g., "#FF5733" for a warm orange-red).
     *
     * <p>Used for:
     * <ul>
     *   <li>Visual display — a colored dot/indicator on the wardrobe card</li>
     *   <li>Potential future feature — color harmony matching algorithm</li>
     * </ul></p>
     */
    @ColumnInfo(name = "color_hex")
    private String colorHex;

    /**
     * The fabric type / material of the clothing item.
     * Examples: "Cotton", "Denim", "Wool", "Polyester", "Linen", "Leather"
     *
     * <p><b>Critical for Smart Stylist (Module 3):</b>
     * Fabric type directly influences weather-based outfit recommendations:
     * <ul>
     *   <li>Heavy fabrics (Wool, Leather, Fleece) are filtered OUT when
     *       the temperature exceeds 28°C.</li>
     *   <li>Light/breathable fabrics (Cotton, Linen) are PREFERRED in
     *       warm weather conditions.</li>
     *   <li>Waterproof fabrics (Nylon, Gore-Tex) may be preferred on
     *       rainy days (potential future enhancement).</li>
     * </ul></p>
     */
    @ColumnInfo(name = "fabric_type")
    private String fabricType;

    /**
     * The purchase price of the item in the user's local currency.
     * Stored as a double to accommodate decimal values (e.g., 49.99).
     *
     * <p><b>Used in Analytics Dashboard (Module 4):</b>
     * The Cost-Per-Wear (CPW) metric is calculated as:
     * <pre>
     *   CPW = purchasePrice / wearCount
     * </pre>
     * A lower CPW indicates better value — the item has been worn many
     * times relative to its cost. This helps users identify:
     * <ul>
     *   <li>High-value staples (low CPW = worn frequently)</li>
     *   <li>Underutilized items (high CPW = rarely worn, consider donating)</li>
     * </ul></p>
     */
    @ColumnInfo(name = "purchase_price")
    private double purchasePrice;

    /**
     * Local file URI pointing to the item's image on disk.
     *
     * <p>Images are stored in the app's internal storage directory:
     * {@code /data/data/com.aiman.smartwardrobe/files/wardrobe_images/}</p>
     *
     * <p><b>Important:</b> All images should ideally have transparent
     * backgrounds (.PNG format) to support the outfit layering canvas
     * in Module 2, where tops, bottoms, and shoes are overlaid on a
     * single FrameLayout.</p>
     *
     * <p>Example path:
     * {@code "/data/data/com.aiman.smartwardrobe/files/wardrobe_images/item_1716700800000.png"}</p>
     */
    @ColumnInfo(name = "image_path")
    private String imagePath;

    /**
     * Timestamp recording when this item was added to the wardrobe.
     * Stored as milliseconds since Unix epoch (System.currentTimeMillis()).
     *
     * <p>Using epoch milliseconds enables:
     * <ul>
     *   <li>Efficient sorting (ORDER BY date_added DESC)</li>
     *   <li>"Recently added" display ordering</li>
     *   <li>Potential future analytics (wardrobe growth over time)</li>
     * </ul></p>
     */
    @ColumnInfo(name = "date_added")
    private long dateAdded;

    /**
     * Optional custom name for the item.
     */
    @ColumnInfo(name = "name")
    private String name;

    /**
     * Whether the item is bookmarked as a favorite.
     */
    @ColumnInfo(name = "is_favorite", defaultValue = "0")
    private boolean isFavorite;

    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================

    /**
     * Default no-argument constructor.
     * <b>Required by Room</b> for entity instantiation via reflection.
     */
    public WardrobeItem() {
    }

    /**
     * Full constructor for creating a new WardrobeItem with all metadata.
     * The {@code itemId} is NOT included because it is auto-generated
     * by Room upon database insertion.
     *
     * @param category      Clothing category (e.g., "T-Shirt", "Jeans")
     * @param colorHex      Hex color string (e.g., "#FF5733")
     * @param fabricType    Fabric material (e.g., "Cotton", "Denim")
     * @param purchasePrice Purchase price in local currency
     * @param imagePath     Local file URI to the item's transparent PNG image
     * @param dateAdded     Epoch timestamp when the item was added
     */
    @Ignore
    public WardrobeItem(String category, String colorHex, String fabricType,
                        double purchasePrice, String imagePath, long dateAdded) {
        this.category = category;
        this.colorHex = colorHex;
        this.fabricType = fabricType;
        this.purchasePrice = purchasePrice;
        this.imagePath = imagePath;
        this.dateAdded = dateAdded;
        this.name = "";
        this.isFavorite = false;
    }

    // =========================================================================
    // GETTERS AND SETTERS
    // =========================================================================
    // Room requires public getters/setters (or public fields) to map
    // Java object fields to SQLite table columns. We use the encapsulated
    // getter/setter pattern for clean, maintainable code.
    // =========================================================================

    public long getItemId() {
        return itemId;
    }

    public void setItemId(long itemId) {
        this.itemId = itemId;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getColorHex() {
        return colorHex;
    }

    public void setColorHex(String colorHex) {
        this.colorHex = colorHex;
    }

    public String getFabricType() {
        return fabricType;
    }

    public void setFabricType(String fabricType) {
        this.fabricType = fabricType;
    }

    public double getPurchasePrice() {
        return purchasePrice;
    }

    public void setPurchasePrice(double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public long getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(long dateAdded) {
        this.dateAdded = dateAdded;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isFavorite() {
        return isFavorite;
    }

    public void setFavorite(boolean favorite) {
        this.isFavorite = favorite;
    }

    // =========================================================================
    // UTILITY METHODS
    // =========================================================================

    /**
     * Returns a human-readable string representation of this WardrobeItem.
     * Useful for debugging, logging, and Logcat output.
     */
    @Override
    public String toString() {
        return "WardrobeItem{" +
                "itemId=" + itemId +
                ", category='" + category + '\'' +
                ", colorHex='" + colorHex + '\'' +
                ", fabricType='" + fabricType + '\'' +
                ", purchasePrice=" + purchasePrice +
                ", imagePath='" + imagePath + '\'' +
                ", dateAdded=" + dateAdded +
                '}';
    }
}
